<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>helloworld-eap-maven-plugin</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <profiles>
        <profile>
            <id>package-with-layers</id>
<!--            <activation>-->
<!--                <activeByDefault>true</activeByDefault>-->
<!--            </activation>-->
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jboss.eap.plugins</groupId>
                        <artifactId>eap-maven-plugin</artifactId>
                        <version>3.0.0.Beta-redhat-SNAPSHOT</version>
                        <configuration>
                            <feature-packs>
                                <feature-pack>
                                    <location>org.jboss.eap:wildfly-ee-galleon-pack:8.2.0.Alpha-redhat-00013</location>
                                </feature-pack>
                                <feature-pack>
                                    <location>org.jboss.eap.cloud:eap-cloud-galleon-pack:3.0.0.Beta-redhat-mnovak-SNAPSHOT</location>
                                </feature-pack>
                            </feature-packs>
                            <layers>
                                <layer>cloud-server</layer>
                            </layers>
                            <bootable-jar>true</bootable-jar>
                        </configuration>
                        <executions>
                            <execution>
                                <id>package-with-layers</id>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>package-with-glow</id>
<!--            <activation>-->
<!--                <property>-->
<!--                    <name>use.glow</name>-->
<!--                    <value>!false</value>-->
<!--                </property>-->
<!--            </activation>-->
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jboss.eap.plugins</groupId>
                        <artifactId>eap-maven-plugin</artifactId>
                        <version>3.0.0.Beta-redhat-SNAPSHOT</version>
                        <configuration>
                            <feature-packs>
                                <feature-pack>
                                    <location>org.jboss.eap:wildfly-ee-galleon-pack:8.2.0.Alpha-redhat-00013</location>
                                </feature-pack>
                                <feature-pack>
                                    <location>org.jboss.eap.cloud:eap-cloud-galleon-pack:3.0.0.Beta-redhat-mnovak-SNAPSHOT</location>
                                </feature-pack>
                            </feature-packs>
                            <discover-provisioning-info>
                                <context>cloud</context>
                                <verbose>true</verbose>
                            </discover-provisioning-info>
                            <bootable-jar>true</bootable-jar>
                        </configuration>
                        <executions>
                            <execution>
                                <id>package-with-glow</id>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>openshift-wildlfy-jar-maven-plugin</id>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-jar-maven-plugin</artifactId>
                        <version>13.0.0.Final</version>
                        <configuration>
<!--                            <feature-packs>-->
<!--                                <feature-pack>-->
<!--                                    <location>org.wildfly:wildfly-galleon-pack:39.0.0.Final</location>-->
<!--                                </feature-pack>-->
<!--                                <feature-pack>-->
<!--                                    <location>org.wildfly.cloud:wildfly-cloud-galleon-pack:9.2.0.Final</location>-->
<!--                                </feature-pack>-->
<!--                            </feature-packs>-->
                            <feature-pack-location>org.jboss.eap.xp:wildfly-galleon-pack:6.0.0.GA-redhat-00024</feature-pack-location>
                            <layers>
                                <layer>web-server</layer>
                                <layer>web-clustering</layer>
                            </layers>
                            <excluded-layers>
                                <layer>deployment-scanner</layer>
                            </excluded-layers>
                            <cloud>
                                <enable-jgroups-password>true</enable-jgroups-password>
                            </cloud>
                            <!-- Channel configuration is added dynamically in EAPPomModifier.java by addWildFlyJarMavenPluginChannel -->
                            <!--
                                                <channels>
                                                    <channel>
                                                        <manifest>
                                                            <groupId>${channel-manifest.groupId}</groupId>
                                                            <artifactId>${channel-manifest.artifactId}</artifactId>
                                                            <version>${channel-manifest.version}</version>
                                                        </manifest>
                                                    </channel>
                                                </channels>
                            -->
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <dependencies>
        <!-- Import the Servlet API, we use provided scope as the API is included in the server -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
            <version>6.1.0</version>
        </dependency>
    </dependencies>
</project>
